package cz.muni.packer.database

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class ItemEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long,
    val name: String,
    val category: String,
    val picture: ByteArray?,
    val currentCount: Int,
    val totalCount: Int,
) {

    // Generated by IDE
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ItemEntity

        if (id != other.id) return false
        if (name != other.name) return false
        if (category != other.category) return false
        if (currentCount != other.currentCount) return false
        if (totalCount != other.totalCount) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + category.hashCode()
        result = 31 * result + currentCount
        result = 31 * result + totalCount
        return result
    }
    // Generated by IDE END
}
