package cz.muni.packer.database.item

/*
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import cz.muni.packer.database.packerlist.PackerListEntity

@Entity(foreignKeys = [ForeignKey(entity = PackerListEntity::class,
                        parentColumns = ["id"],
                        childColumns = ["packerListId"],
                        onDelete = ForeignKey.CASCADE)])
data class ItemEntity(
    @PrimaryKey(autoGenerate = true)
    val id: String,
    val name: String,
    val category: String,
    val picture: ByteArray?,
    val currentCount: Int,
    val totalCount: Int,
    val packerListId: Long
) {

    // Generated by IDE
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ItemEntity

        if (id != other.id) return false
        if (name != other.name) return false
        if (category != other.category) return false
        if (picture != null) {
            if (other.picture == null) return false
            if (!picture.contentEquals(other.picture)) return false
        } else if (other.picture != null) return false
        if (currentCount != other.currentCount) return false
        if (totalCount != other.totalCount) return false
        if (packerListId != other.packerListId) return false

        return true
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + name.hashCode()
        result = 31 * result + category.hashCode()
        result = 31 * result + (picture?.contentHashCode() ?: 0)
        result = 31 * result + currentCount
        result = 31 * result + totalCount
        result = 31 * result + packerListId.hashCode()
        return result
    }
    // Generated by IDE END
}
*/
